version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/mongo
  transaction:
    build:
      context: ./Transaction
    volumes:
      - ./data/app
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/transactions
    ports:
      - "8080:8080"
